#!/bin/bash

# config file generated by home assistant
JSON_FILE="/data/options.json"

# JSON einlesen und Variablen exportieren, falls Datei existiert
if [ -f "$JSON_FILE" ]; then
    while IFS="=" read -r key value; do
        export "$key"="$value"
    done < <(jq -r 'to_entries | .[] | "\(.key)=\(.value)"' "$JSON_FILE")
fi

exec "$@"
