name: Cleanup GHCR images

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
            # token: ${{ secrets.GITHUB_TOKEN }}
            # owner: wastlbava
            # repository: GroBro
            # package: grobro
            dry-run: true
