name: Cleanup GHCR images

on:
  workflow_dispatch:
  schedule:
    - cron: "40 20 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          owner: robertzaage
          repository: GroBro
          package: grobro
