name: Python code check

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  python_version: "3.11"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
    - name: Code - Checkout
      uses: actions/checkout@v4

    - name: Python - Set up Python ${{ env.python_version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python_version }}

    - name: Python - Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Pylint - Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
